apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: flask-app-namespace
data:
  nginx.conf: |
    events {}
    http {
      upstream flask_backend {
        server flask-service:5000;
        server flask-service:5000;
        server flask-service:5000;
      }

      server {
        listen 80;
        location / {
          proxy_pass http://flask_backend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: flask-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-config
