apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: flask-app-namespace
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
